version: 2
jobs:
  rubocop:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers-legacy
      environment:
        RAILS_ENV: test
        POSTGRES_HOST: 127.0.0.1
    - image: circleci/mysql:8.0.19-ram
      environment:
        MYSQL_USER: root
        MYSQL_DB: circle_test
    working_directory: ~/webapp
    steps:
    - checkout
    #- restore_cache:
        #keys:
        #- v1-dependencies-{{ checksum "Gemfile.lock" }}
        #- v1-dependencies-
    - run:
        name: setup bundler
        command: |
          sudo gem update --system
          sudo gem uninstall bundler
          sudo rm /usr/local/bin/bundle
          sudo gem install bundler

    #- run:
        #name: Which bundler?
        #command: bundle -v

    - run: bundle install --jobs=4 --retry=3 path vendor/bundle
    - run: yarn install
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
    - run:
        name: Rubocop
        command: bundle exec rubocop
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/harluz/my_app/compare/d2cc3820e21a4fb2d58cbd09095482d3f10f52c0...2a1529ec1b0ad13fb1d22337ac73738c33cb16cd
  rspec:
    docker:
    - image: circleci/ruby:2.6.3-node-browsers-legacy
      environment:
        RAILS_ENV: test
        POSTGRES_HOST: 127.0.0.1
    - image: circleci/mysql:8.0.19-ram
      environment:
        MYSQL_USER: root
        MYSQL_DB: circle_test
    working_directory: ~/webapp
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-
    - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
    - run: yarn install
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
    - run: bundle exec rake db:create
    - run: bundle exec rake db:schema:load
    - run:
        name: Rspec
        command: bundle exec rspec
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/harluz/my_app/compare/d2cc3820e21a4fb2d58cbd09095482d3f10f52c0...2a1529ec1b0ad13fb1d22337ac73738c33cb16cd
workflows:
  version: 2
  rubocop_rspec:
    jobs:
    - rubocop
    - rspec:
        requires:
        - rubocop
